### ISSUE TITLE
Problems with the code runtime process

### ISSUE THREAD

**Issue by csdzdy** [ritaranx/WANDER#1]
Dear author, we did not find faiss_knn.py in your code. If you could provide this file (faiss_knn.py), we would greatly appreciate it

**Comment by ritaranx** [comment]
Hi!

Thanks for bringing up this issue! The file `faiss_knn.py` you mentioned is actually `dense_retrieval.py`. We changed the file name but forgot to modify the README accordingly. We just fixed this issue. Thank you!

Best,
Ran
